### ISSUE TITLE
Build issues with Array.prototype.includes

### ISSUE THREAD

**Issue by arizzitano** [edx/paragon#204]
As reported by @mikix: Paragon's one use of [Array.prototype.includes](https://github.com/edx/paragon/blob/8746ca10b8c02a8b231d9e09af08959f2830f8d8/src/asInput/index.jsx#L166) is not being compiled down to ES5 in (at least) the static build. We should ensure the proper babel presets and/or polyfills are in place to prevent `asInput` from throwing in IE11 consumers.

**Comment by jaebradley** [comment]
Adding https://github.com/amilajack/eslint-plugin-compat was trying to tackle parts of this issue, but inferring the type of an object is a pretty hard problem - regardless, a short-term solution is using `indexOf` instead of `includes`, I think.

**Comment by mikix** [comment]
Using babel-plugin-array-includes would also work if you prefer using the es7 syntax.

**Comment by jaebradley** [comment]
https://babeljs.io/docs/usage/polyfill/ should do the trick in one fell swoop?

**Comment by thallada** [comment]
@mikix that will only transform usages of `includes` on a literal array unfortunately, e.g. `[1, 2, 3].includes('foo')` ([see pitfalls](https://www.npmjs.com/package/babel-plugin-array-includes#pitfalls)).

@jaebradley I'm wary of including that in Paragon since users of Paragon might want to support a different set of browsers than we do. There are also some issues with including babel-polyfill on the same page twice. You'd have to detect if it was loaded already first. Also, the readme for babel-polyfill suggests that you should use the transform-runtime plugin for libraries so you don't modify globals.

I think it's reasonable to expect users of Paragon to include babel-polyfill themselves if they need to support older browsers.

**Comment by mikix** [comment]
@thallada :man_shrugging: it worked for me to fix paragon on IE11.

**Comment by mikix** [comment]
But just using indexOf for now seems the easiest too.

**Comment by thallada** [comment]
@mikix Oh yeah, you're right it looks like it can transform that, they even have [a test for it](https://github.com/stoeffel/babel-plugin-array-includes/blob/master/test/test.js#L10-L13). I don't understand what that pitfall is referring to now. I guess it doesn't work on function arguments?
