### ISSUE TITLE
React 16 + Enzyme upgrade

### ISSUE THREAD

**Issue by arizzitano** [edx/paragon#45]
Let's do all these in one shot.

**Comment by jaebradley** [comment]
Issues I ran into when implementing this:

* There are, in some cases, pretty significant changes between Enzyme 2 and Enyzme 3
    * [Enyzme 3 Migration Guide](https://github.com/airbnb/enzyme#upgrading-from-enzyme-2x-or-react--16)
    * Impact: test failures that I haven't sorted out
* I think we need to install [`babel-polyfill`](https://babeljs.io/docs/usage/polyfill/)
![image](https://user-images.githubusercontent.com/8136030/32762750-41a83a9c-c8c9-11e7-9ee2-226171bc7b76.png)
  * [This is due to React 16's dependency on `Map` and `Set`](https://reactjs.org/docs/javascript-environment-requirements.html)
     * [Here's the issue discussion on `create-react-app`](https://github.com/facebookincubator/create-react-app/issues/3199)
* I've attached my local dependency tree, along with all missing peer dependency warnings
     * The packages that are triggering these peer dependency warnings are `react-komposer@2.0.0`, `react-treebeard@2.0.3`, `react-simple-di@1.2.0`, and `react-stubber@1.0.0`
     * These peer dependency warnings seem to be due to `@storybook/ui` dependencies, so at the very least these are `devDependency` dependencies.
     * That being said, those particular libraries have open PRs to address these warnings, though there doesn't seem to be much activity on those PRs.

[unmet_peer_dependencies.txt](https://github.com/edx/paragon/files/1469591/unmet_peer_dependencies.txt)

[My branch](https://github.com/edx/paragon/tree/update-dependencies)

**Comment by thallada** [comment]
@jaebradley About that React 16 console error, have you tried to define a dummy pollyfill for `requestAnimationFrame` in the tests like the React docs suggest. I found [this thread, which suggests defines it in a jest `setupFiles` file](https://github.com/facebook/jest/issues/4545#issuecomment-333004504). It also does the weird adapter thing in that one file instead of having to add that to every test file too (I think you might have mentioned this in the FedX meeting).

**Comment by jaebradley** [comment]
Nice, let me try and give that a whirl!
